services:
  db:
    image: postgres:17
    container_name: origis-db
    environment:
      POSTGRES_DB: origis
      POSTGRES_USER: origis
      POSTGRES_PASSWORD: origis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U origis -d origis"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
    container_name: origis-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
#    environment:
#      JDBC_URL
volumes:
  pgdata: