spring.application.name=origin_backend

spring.mvc.servlet.path=/api

#db.url=jdbc:postgresql://localhost:5432/origis
#db.url=jdbc:postgresql://db:5432/origis
#db.username=origis
#db.password=origis


hibernate.hbm2ddl.auto=update
#hibernate.hbm2ddl.auto=create
#hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jakarta.persistence.validation.mode=CALLBACK
